# Conda-forge llvmlite 0.39 issue reproducer

[LLVM Issue #45520](https://github.com/llvm/llvm-project/issues/45520) / [LLVM
Bugzilla 46175](https://bugs.llvm.org/show_bug.cgi?id=46175) appears to manifest
in the conda-forge llvmlite build.

This repo contains a reproducer for the issue using the original triggering IR
from the issue [`bad.ll`](bad.ll) and the IR generated by Numba from the test
[`numba.tests.test_sets.TestTupleSets.test_add_discard`](module.ll).

It also contains the test case from [`llvm_11_consecucutive_registers.patch`](https://github.com/numba/llvmlite/blob/52970defcdd82c68a420e1dc182a814c7c4b16e3/conda-recipes/llvm_11_consecutive_registers.patch) from the [llvmlite repository](https://github.com/numba/llvmlite).
When this test case is used, the failure is as:

```
$ python repro_csec_reg_patch.py
LLVM ERROR: Unknown mismatch in getCopyFromParts!
Aborted (core dumped)
```

`getCopyFromParts()` is the same function that the reproducer from the LLVM bug
tracker and the Numba-generated code cause a failure in.


## Reproduction notes

I have reproduced the issue on a Jetson AGX Xavier. When run, the backtrace /
session looks like:

```
$ gdb -ex run -ex bt -ex "set confirm off" -ex quit --args python numba_repro.py
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
Starting program: /data/gmarkall/miniforge/envs/cf-numba-94/bin/python numba_repro.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
BFD: warning: <in-memory>: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000

Program received signal SIGSEGV, Segmentation fault.
0x0000007fb2eea99c in getCopyFromParts(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue const*, unsigned int, llvm::MVT, llvm::EVT, llvm::Value const*, llvm::Optional<unsigned int>, llvm::Optional<llvm::ISD::NodeType>) [clone .isra.0] ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#0  0x0000007fb2eea99c in getCopyFromParts(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue const*, unsigned int, llvm::MVT, llvm::EVT, llvm::Value const*, llvm::Optional<unsigned int>, llvm::Optional<llvm::ISD::NodeType>) [clone .isra.0] ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#1  0x0000007fb2f2f798 in llvm::SelectionDAGISel::LowerArguments(llvm::Function const&) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#2  0x0000007fb2f8e7ac in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#3  0x0000007fb2f9019c in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) [clone .part.0] ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#4  0x0000007fb2afcd7c in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#5  0x0000007fb28a7ee0 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#6  0x0000007fb28a93f0 in llvm::FPPassManager::runOnModule(llvm::Module&) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#7  0x0000007fb28a6eb0 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#8  0x0000007fb4206ff8 in llvm::MCJIT::emitObject(llvm::Module*) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#9  0x0000007fb42076d0 in llvm::MCJIT::generateCodeForModule(llvm::Module*) ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#10 0x0000007fb42034f0 in llvm::MCJIT::finalizeObject() ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/site-packages/llvmlite/binding/../../../../libLLVM-11.so
#11 0x0000007fb7fbdec0 in ffi_call_SYSV () from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/lib-dynload/../../libffi.so.8
#12 0x0000007fb7fbd438 in ffi_call_int () from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/lib-dynload/../../libffi.so.8
#13 0x0000007fb7828c50 in _ctypes_callproc ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/lib-dynload/_ctypes.cpython-310-aarch64-linux-gnu.so
#14 0x0000007fb7821524 in PyCFuncPtr_call ()
   from /data/gmarkall/miniforge/envs/cf-numba-94/lib/python3.10/lib-dynload/_ctypes.cpython-310-aarch64-linux-gnu.so
#15 0x00000055555d2208 in _PyObject_Call ()
#16 0x00000055555be254 in _PyEval_EvalFrameDefault ()
#17 0x0000005555669bd0 in _PyEval_Vector ()
#18 0x00000055555d26cc in _PyObject_FastCallDictTstate ()
#19 0x00000055555d2a20 in _PyObject_Call_Prepend ()
#20 0x0000005555623240 in slot_tp_call ()
#21 0x00000055555d24f0 in _PyObject_MakeTpCall ()
#22 0x00000055555c30a0 in _PyEval_EvalFrameDefault ()
#23 0x0000005555669bd0 in _PyEval_Vector ()
#24 0x00000055555c0850 in _PyEval_EvalFrameDefault ()
#25 0x0000005555669bd0 in _PyEval_Vector ()
#26 0x00000055555c07ec in _PyEval_EvalFrameDefault ()
#27 0x0000005555669bd0 in _PyEval_Vector ()
#28 0x0000005555669dc0 in PyEval_EvalCode ()
#29 0x00000055556a854c in run_eval_code_obj ()
#30 0x00000055556a87e8 in run_mod ()
#31 0x00000055556a8918 in pyrun_file ()
#32 0x00000055556aaf34 in _PyRun_SimpleFileObject ()
#33 0x00000055556ab510 in _PyRun_AnyFileObject ()
#34 0x00000055555c586c in Py_RunMain ()
#35 0x00000055555c61f0 in Py_BytesMain ()
#36 0x0000007fb7d6c720 in __libc_start_main (main=0x0, argc=0, argv=0x0, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, 
    stack_end=<optimised out>) at ../csu/libc-start.c:310
#37 0x00000055555c4adc in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
